'use strict';
require('dotenv').config();

//Mailer part start

let nodemailer = require('nodemailer');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; // remove this line in production and add SSL certificate

let transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USER || '', /*use your mail id*/
    pass: process.env.EMAIL_PASS || ''   /*use your passkey generated by your mail provider account*/
  }
});

let mailOptions = {
  to: process.env.SENDER_MAIL || '', //sender's mail id
  subject: 'Sending Email using Node.js',
  text: 'That was easy!'
};

transporter.sendMail(mailOptions, (error, info) => {
  if (error) {
    console.log(error);
  } else {
    console.log('Email sent: ' + info.response);
  }
});
//mailer part end
